# サイトの設定
site_name: setup-ctrpf-dev
site_url: https://ponpoko094.github.io/setup-ctrpf-dev-mkdocs/

# リポジトリの設定
repo_name: ponpoko094/setup-ctrpf-dev
repo_url: https://github.com/ponpoko094/setup-ctrpf-dev
edit_uri: ""

# 著作権表示
copyright: "Copyright © 2022 - ponpoko094"

# テーマ
theme:
    name: material
    font:
        text: "Noto Sans JP"
        code: "Consolas"
    language: ja
    features:
        # - navigation.tabs
    palette:
        - scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode
    icon:
        logo: fontawesome/solid/book

# cssファイルの読み込み
extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

# JavaScriptファイルの読み込み
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/ponpoko094

# 拡張機能の設定
markdown_extensions:
    - abbr
    - admonition
    - footnotes
    - def_list
    - mdx_math:
          enable_dollar_delimiter: true
    - fontawesome_markdown
    - mdx_truly_sane_lists
    - pymdownx.keys
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
          use_pygments: true
          noclasses: true
          pygments_style: monokai
          linenums: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.snippets
    - pymdownx.superfences

# # 拡張を入れる。
plugins:
    # GithubのCommit時間をページに表示
    - git-revision-date-localized:
          type: iso_datetime
          timezone: Japan
          fallback_to_build_date: false
          enable_creation_date: true
          enabled: true
    # 日本語対応
    - search:
          lang:
              - en
              - ja
        # .pagesでページ階層を指定できるようにする
    - awesome-pages

nav:
